[package]
name = "canonicaljson-rs"
version = "1.0.0"
authors = ["Mathieu Leplatre <mathieu@mozilla.com>"]
edition = "2018"

[lib]
name = "canonicaljson"  # python package name
crate-type = ["cdylib"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
canonical_json = { path = "../remote-settings-client/src/client/signatures/canonical_json" }

[dependencies.pyo3]
version = "0.11"
features = ["extension-module"]
